### ISSUE TITLE
JavaScript Error on Win 11 Dev

### ISSUE THREAD

**Issue by zegmin** [th-ch/youtube-music#1018]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. TypeError: Cannot read properties of undefined (reading 'global')
    at ElectronStore._migrate (C:\Users\user\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\conf\dist\source\index.js:429:23)
    at new Conf (C:\Users\user\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\conf\dist\source\index.js:150:18)
    at new ElectronStore (C:\Users\user\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\electron-store\index.js:69:3)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\youtube-music\resources\app.asar\config\store.js:92:18)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)

[OK]

**Comment by Araxeus** [comment]
It seems your config got corrupted somehow.

>JavaScript Error on Win 11 Dev 

`Dev` meaning you cloned the repo and built it yourself?

If not, then how did you install and is this your first time installing?

please post your config.json here - you can find it's containg folder here:
* Windows: `%AppData%/Youtube Music` (`MyUser/AppData/Roaming/Youtube Music`)
* Linux: `~/.config/Youtube Music`
* MacOS: `~/Library/Application\ Support/YouTube\ Music/config.json`

----

If you did clone and build yourself, then, Try maybe adding after this line:

https://github.com/th-ch/youtube-music/blob/7cbc99fc1906e946e4a29a31259da4c63515aa50/config/store.js#L40

```js
if (!options) return;
```

----

if not then you can download this file:

**Comment by zegmin** [comment]
Dev meaning I'm on Win 11 Developer Preview, I installed using the setup .exe and also tried the standalone .exe, issue persisted regardless. This is my first time installing in a long while, though I think I may have used the application previously over a year ago.

config.json
{
	"window-size": {
		"width": 1101,
		"height": 551
	},
	"url": "https://music.youtube.com/",
	"plugins": [
		"navigation",
		"shortcuts",
		"adblocker"
	],
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": true,
		"startAtLogin": false
	},
	"window-position": {
		"x": 170,
		"y": 131
	},
	"window-maximized": false,
	"__internal__": {
		"migrations": {
			"version": ">=1.13.0"
		}
	}
}

**Comment by zegmin** [comment]
Okay actually I am realizing I did install back in 2020, I deleted that appdata folder and now the application works, thank you and sorry for the trouble.

**Comment by Araxeus** [comment]
Still a bug tho, so thanks ill open up a PR that should fix it
