### ISSUE TITLE
[Bug] App crashes on connection failure to `lh3.googleusercontent.com`

### ISSUE THREAD

**Issue by jrabinow** [th-ch/youtube-music#163]
Works with some songs (try https://music.youtube.com/watch?v=WHq96QRBaHc&feature=share), with other songs it doesn't.

Platform: Mac OS X
Repro steps:
1/ add `127.0.0.1   googlehosted.l.googleusercontent.com` to your hosts file
2/ open the app, play the song
3/ toggle play/pause 4-5 times (speed doesn't matter, works with both media hotkey and clicking the button). When pressing play the app will crash.

Looking at the traceback, `(node:22176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` it looks like the electron project decided that this crash is not a bug, it's a "feature"

Full traceback:
```
$ /Applications/YouTube\ Music.app/Contents/MacOS/YouTube\ Music
Loaded plugin - adblocker
Loaded plugin - downloader
Loaded plugin - navigation
Loaded plugin - shortcuts
Loaded plugin - auto-confirm-when-paused
Loaded plugin - notifications
Checking for update
Update for version 1.10.0 is not available (latest version: 1.10.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
(node:22176) UnhandledPromiseRejectionWarning: FetchError: request to https://lh3.googleusercontent.com/FJk0uBoJepkN1j3rPTLJxk7xUGHHNqxPVy0yf4jSAJKFB-EmCIhCkjA-YIl5vCKlNT-ZPMCnbhZpQOQ-=w60-h60-l90-rj failed, reason: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/Applications/YouTube Music.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:22176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandle
d promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22176) UnhandledPromiseRejectionWarning: FetchError: request to https://lh3.googleusercontent.com/FJk0uBoJepkN1j3rPTLJxk7xUGHHNqxPVy0yf4jSAJKFB-EmCIhCkjA-YIl5vCKlNT-ZPMCnbhZpQOQ-=w60-h60-l90-rj failed, reason: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/Applications/YouTube Music.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:22176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandle
d promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Error: async hook stack has become corrupted (actual: 76, expected: 0)
 1: 0x10735e7af ElectronInitializeICUandStartNode [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x109b0aa7e node::CallbackScope::~CallbackScope() [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x109b0a5ae node::CallbackScope::~CallbackScope() [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x109b48d54 node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x107207efd uv_timer_get_repeat [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x10720b3ea uv_run [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x10735e16c ElectronInitializeICUandStartNode [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x1083292f9 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x10833694f v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x108336560 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x1083684f0 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x10836500a v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x108367ecf v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x7fff2043ca0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
15: 0x7fff2043c974 __CFRunLoopDoSource0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
16: 0x7fff2043c6ef __CFRunLoopDoSources0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
17: 0x7fff2043b121 __CFRunLoopRun [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
18: 0x7fff2043a6ce CFRunLoopRunSpecific [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
19: 0x7fff286bf6d0 RunCurrentEventLoopInMode [/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox]
20: 0x7fff286bf4cc ReceiveNextEventCommon [/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox]
21: 0x7fff286bf1ef _BlockUntilNextEventMatchingListInModeWithFilter [/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox]
22: 0x7fff22c57de9 _DPSNextEvent [/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit]
23: 0x7fff22c565af -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] [/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit]
24: 0x7fff22c48b0a -[NSApplication run] [/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit]
25: 0x108368a86 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
26: 0x108367a62 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
27: 0x108336ea1 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
28: 0x1083155d9 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
29: 0x10ad58914 v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes() const [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
30: 0x107fb5d02 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
31: 0x107fb17c9 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
32: 0x107f76e21 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
33: 0x107f76b46 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
34: 0x1077c0f0e ElectronInitializeICUandStartNode [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
35: 0x1077c1412 ElectronInitializeICUandStartNode [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
36: 0x10721cc08 ElectronMain [/Applications/YouTube Music.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
37: 0x101370edd  [/Applications/YouTube Music.app/Contents/MacOS/YouTube Music]
38: 0x7fff2035f621 start [/usr/lib/system/libdyld.dylib]
39: 0x1
```

**Comment by th-ch** [comment]
Hey @jrabinow, thanks for the detailed report! https://github.com/th-ch/youtube-music/commit/5842a6d42f242a6093b1e2c0d5fc6bb965014e7b changes the code to handle these errors and log them - it should solve the issue of uncaught exceptions and avoid crashes, it will ship in the next version!

**Comment by jrabinow** [comment]
Awesome, thank you! :-)

I'm closing the issue, but feel free to reopen if that's a mistake
