### ISSUE TITLE
after play video 2-3min app is stop all time

### ISSUE THREAD

**Issue by tee4341** [th-ch/youtube-music#773]
error code

Build version: 3.7.12 
Current date: 2022-07-02 08:13:53 
Device: Teclast P10_HD_ROW 
 
Stack trace:  
kotlinx.coroutines.DispatchException: Unexpected exception running CancellableContinuation(DispatchedContinuation[CommonPool, ṏօⱺ$Ố@ef97ae8]){Completed}@b1c3501
	at ỌỐȌ.ṏỡ(Unknown Source:120)
	at ỌőỘ.run(Unknown Source:0)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at ỌỐȌ.ơ(Unknown Source:62)
	at ỌỞỞ.Ȫ(Unknown Source:7)
	at Ọꝍṍ$Ọ.ṏ(Unknown Source:18)
	at Ọꝍṍ.ṍ(Unknown Source:36)
	at Ọꝍṍ.Ṓ(Unknown Source:182)
	at Ọꝍṍ.ȯ(Unknown Source:256)
	at Ọꝍṍ.Ǭ(Unknown Source:0)
	at Ọőǭ.Ở(Unknown Source:8)
	at ỌȎÕ.Ở(Unknown Source:36)
	at ỌỐȌ.ṏỡ(Unknown Source:80)
	... 7 more
	Suppressed: java.lang.ExceptionInInitializerError
		at ỌꝍȬ.ṏ(Unknown Source:0)
		at ỌỐȌ.ơ(Unknown Source:50)
		... 16 more
	Caused by: java.lang.SecurityException: cannot verify signature block file META-INF/CERT
		at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:295)
		at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
		at java.util.jar.JarVerifier.processEntry(JarVerifier.java:317)
		at java.util.jar.JarVerifier.update(JarVerifier.java:229)
		at java.util.jar.JarFile.initializeVerifier(JarFile.java:374)
		at java.util.jar.JarFile.getInputStream(JarFile.java:441)
		at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:177)
		at java.net.URL.openStream(URL.java:1072)
		at java.util.ServiceLoader.parse(ServiceLoader.java:305)
		at java.util.ServiceLoader.access$200(ServiceLoader.java:183)
		at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:358)
		at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:402)
		at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:488)
		at Ọờɵ.ṓ(Unknown Source:14)
		at Ọờɵ.ố(Unknown Source:21)
		at Ọờɵ.ǫ(Unknown Source:54)
		at ỌꝍȬ.<clinit>(Unknown Source:15)
		... 18 more
Caused by: ṏօⱺ$Ố$ṏ
	at ṏօⱺ$Ố.Ȏ(Unknown Source:267)
	at ỌȎÕ.Ở(Unknown Source:11)
	... 8 more

User actions: 
2022-07-02 08:08:42: MainActivity created
2022-07-02 08:08:42: MainActivity resumed

**Comment by Araxeus** [comment]
I think you might be talking about another app, the error you posted says `java`/`kotlin`

this app is not written in java
