### ISSUE TITLE
Can't create dev build on Ubuntu

### ISSUE THREAD

**Issue by Equinoxx4978** [th-ch/youtube-music#906]
I followed the "Dev" steps but it throws an error when I use the `yarn` command

Error:
```
➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍

➤ YN0000: ┌ Resolution step
➤ YN0014: │ Simple-YouTube-Age-Restriction-Bypass@https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?[...]: Only some patterns can be imported from legacy lockfiles (not "https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?v2.5.4#4cdc95d7614baa3fdfe334ebf6b8a99b0d8347f0")
➤ YN0001: │ Error: Simple-YouTube-Age-Restriction-Bypass@https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?[...] isn't supported by any available resolver
    at Wf.getResolverByDescriptor (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:391:1647)
    at Wf.bindDescriptor (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:391:1036)
    at Z (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:439:6905)
➤ YN0000: └ Completed in 0s 504ms
➤ YN0000: Failed with errors in 0s 514ms
```

Just want to use the dev build for fixed discord rich presence, if you know a way to do it without the dev build, letting me know would be appreciated!

**Comment by Zo-Bro-23** [comment]
Do you have `node_modules` in the same directory? That is, did you use `npm` to install packages?

**Comment by Zo-Bro-23** [comment]
Try building from scratch again:
- Download [this](https://github.com/th-ch/youtube-music/archive/3605e32b2531efa3d124ef509ac2612347bf4679.zip) zip file
- Unzip it
- Navigate to the extracted folder in Terminal
- Type the following one by one:
  - yarn
  - npm i rimraf
  - yarn build:win

**Comment by Equinoxx4978** [comment]
I get these errors when running those commands:

`yarn`:
```
➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍

➤ YN0000: ┌ Resolution step
➤ YN0014: │ Simple-YouTube-Age-Restriction-Bypass@https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?[...]: Only some patterns can be imported from legacy lockfiles (not "https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?v2.4.6#ac26ebb688667ce4ec6566ffbd3a75dbe2ac9a55")
➤ YN0001: │ Error: Simple-YouTube-Age-Restriction-Bypass@https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?[...] isn't supported by any available resolver
    at Wf.getResolverByDescriptor (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:391:1647)
    at Wf.bindDescriptor (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:391:1036)
    at Z (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:439:6905)
➤ YN0000: └ Completed in 0s 504ms
➤ YN0000: Failed with errors in 0s 512ms
```

`npm i rimraf`:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: youtube-music@1.18.0
npm ERR! Found: electron@20.1.1
npm ERR! node_modules/electron
npm ERR!   dev electron@"^20.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer electron@"^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0" from custom-electron-prompt@1.5.0
npm ERR! node_modules/custom-electron-prompt
npm ERR!   custom-electron-prompt@"^1.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/josh/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/josh/.npm/_logs/2022-12-03T02_14_46_365Z-debug-0.log
```

`yarn build:linux`:
```
Internal Error: youtube-music@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at pQ.getCandidates (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:435:5146)
    at Wf.getCandidates (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:391:1264)
    at /home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:439:7695
    at Rf (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:390:8965)
    at ge (/home/josh/.cache/node/corepack/yarn/3.3.0/yarn.js:439:7675)
```

**Comment by Zo-Bro-23** [comment]
Did you try deleting the folder and cloning the repo again? Also try using an earlier commit like https://github.com/th-ch/youtube-music/commit/3605e32b2531efa3d124ef509ac2612347bf4679
