### ISSUE TITLE
Unable to build app to linux

### ISSUE THREAD

**Issue by astahjmo** [th-ch/youtube-music#933]
I just can't build the app to linux

Os: Arch linux
Node version: 16  && 14 

Steps: 

- clone master branch
- use yarn or yarn install
- use yarn build:linux

<details><summary>full log about yarn</summary>
<p>

```
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "yargs-parser@18.1.3" is incompatible with requested versi
on "yargs-parser@^21.1.1"
warning Resolution field "minimist@1.2.6" is incompatible with requested version "m
inimist@1.2.0"
warning Resolution field "yargs-parser@18.1.3" is incompatible with requested versi
on "yargs-parser@^4.2.0"
warning Resolution field "yargs-parser@18.1.3" is incompatible with requested versi
on "yargs-parser@^20.2.9"
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > custom-electron-prompt@1.5.0" has incorrect peer dependency "electron@^
10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 || ^17.0.0
 || ^18.0.0".
warning " > custom-electron-titlebar@4.1.5" has incorrect peer dependency "electron
@>20".
warning "xo > eslint-import-resolver-webpack@0.13.2" has unmet peer dependency "web
pack@>=1.11.0".
[5/5] Building fresh packages...
$ yarn run icon && yarn run plugins
yarn run v1.22.19
$ rimraf assets/generated && electron-icon-maker --input=assets/youtube-music.png -
-output=assets/generated
{
  i: 'assets/youtube-music.png',
  input: 'assets/youtube-music.png',
  o: 'assets/generated',
  output: 'assets/generated'
}
Created /tmp/youtube-music/assets/generated/icons/png/16.png
Created /tmp/youtube-music/assets/generated/icons/png/24.png
Created /tmp/youtube-music/assets/generated/icons/png/32.png
Created /tmp/youtube-music/assets/generated/icons/png/48.png
Created /tmp/youtube-music/assets/generated/icons/png/64.png
Created /tmp/youtube-music/assets/generated/icons/png/128.png
Created /tmp/youtube-music/assets/generated/icons/png/256.png
Created /tmp/youtube-music/assets/generated/icons/png/512.png
Created /tmp/youtube-music/assets/generated/icons/png/1024.png
Icon generetor from PNG:
  src: /tmp/youtube-music/assets/generated/icons/png
  dir: /tmp/youtube-music/assets/generated/icons/mac
ICNS:
  Create: /tmp/youtube-music/assets/generated/icons/mac/icon.icns
Icon generetor from PNG:
  src: /tmp/youtube-music/assets/generated/icons/png
  dir: /tmp/youtube-music/assets/generated/icons/win
ICO:
  Create: /tmp/youtube-music/assets/generated/icons/win/icon.ico
Renaming PNGs to Electron Format
Renamed 16.png to 16x16.png
Renamed 24.png to 24x24.png
Renamed 32.png to 32x32.png
Renamed 48.png to 48x48.png
Renamed 64.png to 64x64.png
Renamed 128.png to 128x128.png
Renamed 256.png to 256x256.png
Renamed 512.png to 512x512.png
Renamed 1024.png to 1024x1024.png

 ALL DONE
Done in 4.39s.
```
yarn run v1.22.19
$ yarn run plugin:adblocker
$ rimraf plugins/adblocker/ad-blocker-engine.bin && node plugins/adblocker/blocker.
js
Successfully generated adBlocker engine.
Done in 1.99s.
Done in 50.14s.

</p>
</details>

<details><summary>full log about yarn build:linux</summary>
<p>

```$ yarn build:linux
yarn run v1.22.19
$ yarn run clean && electron-builder --linux
$ rimraf dist
  • electron-builder  version=23.6.0 os=6.1.1-arch1-1
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=abstract-socket@2.1.1, register-scheme@0.0.2 platform=linux arch=x64
  • rebuilding native dependency  name=register-scheme version=0.0.2
  • rebuilding native dependency  name=abstract-socket version=2.1.1
  ⨯ cannot execute  cause=exit status 1
$ node-gyp rebuild
    make: Entering directory '/tmp/youtube-music/node_modules/abstract-socket/build'
      CXX(target) Release/obj.target/bindings/src/abstract_socket.o
    make: Leaving directory '/tmp/youtube-music/node_modules/abstract-socket/build'
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
                    errorOut=gyp info it worked if it ends with ok
    gyp info using node-gyp@5.1.0
    gyp info using node@14.21.2 | linux | x64
    gyp info find Python using Python version 3.10.9 found at "/usr/bin/python"
    gyp info spawn /usr/bin/python
    gyp info spawn args [
    gyp info spawn args   '/home/astaroth/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/tmp/youtube-music/node_modules/abstract-socket/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/astaroth/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/astaroth/.electron-gyp/20.1.1/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/astaroth/.electron-gyp/20.1.1',
    gyp info spawn args   '-Dnode_gyp_dir=/home/astaroth/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/astaroth/.electron-gyp/20.1.1/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/tmp/youtube-music/node_modules/abstract-socket',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    In file included from ../../nan/nan.h:58,
                     from ../src/abstract_socket.cc:5:
    /home/astaroth/.electron-gyp/20.1.1/include/node/node.h:27:2: error: #error "It looks like you are building this native module without using the right config.gypi.  This normally means that you need to update electron-rebuild (>=3.2.8) or node-gyp (>=8.4.0) if you're building modules directly."
       27 | #error "It looks like you are building this native module without using the right config.gypi.  This normally means that you need to update electron-rebuild (>=3.2.8) or node-gyp (>=8.4.0) if you're building modules directly."
          |  ^~~~~
    In file included from /home/astaroth/.electron-gyp/20.1.1/include/node/v8-object.h:9,
                     from /home/astaroth/.electron-gyp/20.1.1/include/node/v8-array-buffer.h:13,
                     from /home/astaroth/.electron-gyp/20.1.1/include/node/v8.h:24,
                     from /home/astaroth/.electron-gyp/20.1.1/include/node/node.h:69:
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-maybe.h:106:45: error: ‘is_lvalue_reference_v’ is not a member of ‘std’; did you mean ‘is_lvalue_reference’?
      106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
          |                                             ^~~~~~~~~~~~~~~~~~~~~
          |                                             is_lvalue_reference
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-maybe.h:106:66: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
      106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
          |                                                                  ^
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-maybe.h:106:67: error: template argument 1 is invalid
      106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
          |                                                                   ^
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-maybe.h:106:71: error: expected unqualified-id before ‘>’ token
      106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
          |                                                                       ^
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-maybe.h:123:43: error: ‘is_lvalue_reference_v’ is not a member of ‘std’; did you mean ‘is_lvalue_reference’?
      123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
          |                                           ^~~~~~~~~~~~~~~~~~~~~
          |                                           is_lvalue_reference
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-maybe.h:123:64: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
      123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
          |                                                                ^
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-maybe.h:123:65: error: template argument 1 is invalid
      123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
          |                                                                 ^
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-maybe.h:123:70: error: expected unqualified-id before ‘=’ token
      123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
          |                                                                      ^
    In file included from ../../nan/nan.h:178:
    ../../nan/nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’
       55 | typedef v8::Local<v8::AccessorSignature> Sig;
          |                       ^~~~~~~~~~~~~~~~~
    ../../nan/nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’
    ../../nan/nan_callbacks.h:55:40: error: template argument 1 is invalid
       55 | typedef v8::Local<v8::AccessorSignature> Sig;
          |                                        ^
    ../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, GetterCallback, SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, imp::Sig)’:
    ../../nan/nan.h:2544:19: error: no matching function for call to ‘v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&, Nan::imp::Sig&)’
     2544 |   tpl->SetAccessor(
          |   ~~~~~~~~~~~~~~~~^
     2545 |       name
          |       ~~~~         
     2546 |     , getter_
          |     ~~~~~~~~~      
     2547 |     , setter_
          |     ~~~~~~~~~      
     2548 |     , obj
          |     ~~~~~          
     2549 |     , settings
          |     ~~~~~~~~~~     
     2550 |     , attribute
          |     ~~~~~~~~~~~    
     2551 |     , signature);
          |     ~~~~~~~~~~~~   
    In file included from /home/astaroth/.electron-gyp/20.1.1/include/node/v8-function.h:15,
                     from /home/astaroth/.electron-gyp/20.1.1/include/node/v8.h:33:
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-template.h:807:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
      807 |   void SetAccessor(
          |        ^~~~~~~~~~~
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-template.h:812:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
      812 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
          |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-template.h:814:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
      814 |   void SetAccessor(
          |        ^~~~~~~~~~~
    /home/astaroth/.electron-gyp/20.1.1/include/node/v8-template.h:819:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
      819 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
          |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../src/abstract_socket.cc: At global scope:
    /home/astaroth/.electron-gyp/20.1.1/include/node/node.h:862:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
      862 |       (node::addon_register_func) (regfunc),                          \
          |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/astaroth/.electron-gyp/20.1.1/include/node/node.h:896:3: note: in expansion of macro ‘NODE_MODULE_X’
      896 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
          |   ^~~~~~~~~~~~~
    ../src/abstract_socket.cc:181:1: note: in expansion of macro ‘NODE_MODULE’
      181 | NODE_MODULE(abstract_socket, Initialize)
          | ^~~~~~~~~~~
    make: *** [bindings.target.mk:119: Release/obj.target/bindings/src/abstract_socket.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/astaroth/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
    gyp ERR! System Linux 6.1.1-arch1-1
    gyp ERR! command "/home/astaroth/.nvm/versions/node/v14.21.2/bin/node" "/home/astaroth/.nvm/versions/node/v14.21.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /tmp/youtube-music/node_modules/abstract-socket
    gyp ERR! node -v v14.21.2
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok 
error Command failed with exit code 1.
    
                    command=/home/astaroth/.nvm/versions/node/v14.21.2/bin/node /usr/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/tmp/youtube-music/node_modules/abstract-socket
error Command failed with exit code 1`

</p>
</details>

**Comment by robinpdev** [comment]
I'm also getting the same gyp error. using Node version 19
